/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoSearchRouteImport } from './routes/demo/search'
import { Route as DemoServerFnRouteImport } from './routes/demo/server-fn'
import { Route as DemoStreamRouteImport } from './routes/demo/stream'
import { Route as DemoSsrIndexRouteImport } from './routes/demo/ssr/index'
import { Route as DemoSsrClientRouteImport } from './routes/demo/ssr/client'
import { Route as DemoSsrDataOnlyRouteImport } from './routes/demo/ssr/data-only'
import { Route as DemoSsrFullRouteImport } from './routes/demo/ssr/full'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSearchRoute = DemoSearchRouteImport.update({
  id: '/demo/search',
  path: '/demo/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoServerFnRoute = DemoServerFnRouteImport.update({
  id: '/demo/server-fn',
  path: '/demo/server-fn',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStreamRoute = DemoStreamRouteImport.update({
  id: '/demo/stream',
  path: '/demo/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSsrIndexRoute = DemoSsrIndexRouteImport.update({
  id: '/demo/ssr/',
  path: '/demo/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSsrClientRoute = DemoSsrClientRouteImport.update({
  id: '/demo/ssr/client',
  path: '/demo/ssr/client',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSsrDataOnlyRoute = DemoSsrDataOnlyRouteImport.update({
  id: '/demo/ssr/data-only',
  path: '/demo/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSsrFullRoute = DemoSsrFullRouteImport.update({
  id: '/demo/ssr/full',
  path: '/demo/ssr/full',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/search': typeof DemoSearchRoute
  '/demo/server-fn': typeof DemoServerFnRoute
  '/demo/stream': typeof DemoStreamRoute
  '/demo/ssr/client': typeof DemoSsrClientRoute
  '/demo/ssr/data-only': typeof DemoSsrDataOnlyRoute
  '/demo/ssr/full': typeof DemoSsrFullRoute
  '/demo/ssr/': typeof DemoSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/search': typeof DemoSearchRoute
  '/demo/server-fn': typeof DemoServerFnRoute
  '/demo/stream': typeof DemoStreamRoute
  '/demo/ssr/client': typeof DemoSsrClientRoute
  '/demo/ssr/data-only': typeof DemoSsrDataOnlyRoute
  '/demo/ssr/full': typeof DemoSsrFullRoute
  '/demo/ssr': typeof DemoSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/search': typeof DemoSearchRoute
  '/demo/server-fn': typeof DemoServerFnRoute
  '/demo/stream': typeof DemoStreamRoute
  '/demo/ssr/client': typeof DemoSsrClientRoute
  '/demo/ssr/data-only': typeof DemoSsrDataOnlyRoute
  '/demo/ssr/full': typeof DemoSsrFullRoute
  '/demo/ssr/': typeof DemoSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/search'
    | '/demo/server-fn'
    | '/demo/stream'
    | '/demo/ssr/client'
    | '/demo/ssr/data-only'
    | '/demo/ssr/full'
    | '/demo/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/search'
    | '/demo/server-fn'
    | '/demo/stream'
    | '/demo/ssr/client'
    | '/demo/ssr/data-only'
    | '/demo/ssr/full'
    | '/demo/ssr'
  id:
    | '__root__'
    | '/'
    | '/demo/search'
    | '/demo/server-fn'
    | '/demo/stream'
    | '/demo/ssr/client'
    | '/demo/ssr/data-only'
    | '/demo/ssr/full'
    | '/demo/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoSearchRoute: typeof DemoSearchRoute
  DemoServerFnRoute: typeof DemoServerFnRoute
  DemoStreamRoute: typeof DemoStreamRoute
  DemoSsrClientRoute: typeof DemoSsrClientRoute
  DemoSsrDataOnlyRoute: typeof DemoSsrDataOnlyRoute
  DemoSsrFullRoute: typeof DemoSsrFullRoute
  DemoSsrIndexRoute: typeof DemoSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/search': {
      id: '/demo/search'
      path: '/demo/search'
      fullPath: '/demo/search'
      preLoaderRoute: typeof DemoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/server-fn': {
      id: '/demo/server-fn'
      path: '/demo/server-fn'
      fullPath: '/demo/server-fn'
      preLoaderRoute: typeof DemoServerFnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/stream': {
      id: '/demo/stream'
      path: '/demo/stream'
      fullPath: '/demo/stream'
      preLoaderRoute: typeof DemoStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ssr/': {
      id: '/demo/ssr/'
      path: '/demo/ssr'
      fullPath: '/demo/ssr/'
      preLoaderRoute: typeof DemoSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ssr/client': {
      id: '/demo/ssr/client'
      path: '/demo/ssr/client'
      fullPath: '/demo/ssr/client'
      preLoaderRoute: typeof DemoSsrClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ssr/data-only': {
      id: '/demo/ssr/data-only'
      path: '/demo/ssr/data-only'
      fullPath: '/demo/ssr/data-only'
      preLoaderRoute: typeof DemoSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ssr/full': {
      id: '/demo/ssr/full'
      path: '/demo/ssr/full'
      fullPath: '/demo/ssr/full'
      preLoaderRoute: typeof DemoSsrFullRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoSearchRoute: DemoSearchRoute,
  DemoServerFnRoute: DemoServerFnRoute,
  DemoStreamRoute: DemoStreamRoute,
  DemoSsrClientRoute: DemoSsrClientRoute,
  DemoSsrDataOnlyRoute: DemoSsrDataOnlyRoute,
  DemoSsrFullRoute: DemoSsrFullRoute,
  DemoSsrIndexRoute: DemoSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
